version: "3.8"

services:
  blog-app:
    build: .
    container_name: blog-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: blog_db
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: b15f7819606774c89cbc1477c9dcbf149683af67ed2ca3e875718850c39330ce
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
    ports:
      - "8080:8080"
  mysql:
    image: mysql
    container_name: blog-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
volumes:
  mysql_data:
