server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:blog_db}

huggingface:
  api:
    key: ${HUGGINGFACE_API_KEY}
    url: https://api-inference.huggingface.co/models/facebook/bart-large-cnn

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days

  images:
    link: http://localhost:8080/api/v1/images/
